name: Auto-Signer Scheduler

on:
  workflow_dispatch: {}

permissions:
  issues: write
  actions: write


jobs:
  scan-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Scan pending auto-sign issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENCRYPTION_KEY: ${{ secrets.PASSWORD_ENCRYPTION_KEY }}

        run: |
          echo "Fetching pending issues..."

          issues=$(gh issue list \
            --label "auto-sign:pending" \
            --state open \
            --json number,title,body)

          now=$(TZ=Europe/Warsaw date +"%Y-%m-%dT%H:%M:%S")

          echo $now

          echo "$issues" | jq -c '.[]' | while read issue; do
            number=$(echo "$issue" | jq -r '.number')
            body=$(echo "$issue" | jq -r '.body')
          
            # Normalize issue body
            body=$(echo "$body" | tr -d '\r' | sed 's/\\n/\n/g')
          
            echo "Normalized body:"
            echo "$body"
          
            join_at=$(echo "$body" | grep -m1 '^[[:space:]]*join_at=' | cut -d= -f2)
          
            echo "join_at=$join_at"
          
            if [ -z "$join_at" ]; then
              echo "Issue #$number has no join_at, skipping"
              continue
            fi
          
            if [[ "$join_at" < "$now" ]]; then
              echo "Issue #$number is due → processing"
          
              gh issue edit "$number" \
                --remove-label "auto-sign:pending" \
                --add-label "auto-sign:processing"
                
          
              email=$(echo "$body" | grep -m1 '^[[:space:]]*email=' | cut -d= -f2)

              echo "Email:"
              echo $email
              
              password_enc=$(echo "$body" | grep -m1 '^[[:space:]]*password=' | cut -d= -f2-)

              echo "Password enc"
              echo $password_enc
              password=$(echo "$password_enc" | openssl enc -aes-256-cbc -a -d -salt -pass pass:"$ENCRYPTION_KEY")
              class_name=$(echo "$body" | grep -m1 '^[[:space:]]*class_name=' | cut -d= -f2)
              class_date=$(echo "$body" | grep -m1 '^[[:space:]]*class_date=' | cut -d= -f2)
              class_time=$(echo "$body" | grep -m1 '^[[:space:]]*class_time=' | cut -d= -f2)
          
              gh workflow run auto-signer.yml \
                -f issue_number="$number" \
                -f email="$email" \
                -f password="$password" \
                -f class_name="$class_name" \
                -f class_date="$class_date" \
                -f class_time="$class_time"
            else
              echo "Issue #$number not due yet"
            fi
          done
